#!/usr/bin/env bash
set -Eeuo pipefail

source_dir="${FGC_SHELL_SOURCE_DIR:?FGC_SHELL_SOURCE_DIR is required}"
target_dir="${XDG_CONFIG_HOME:-$HOME/.config}/fedora-gnome-custom/bash"
state_dir="${XDG_STATE_HOME:-$HOME/.local/state}/fedora-gnome-custom/bash"
bashrc="$HOME/.bashrc"
start_marker='# >>> fedora-gnome-custom bash ux >>>'
end_marker='# <<< fedora-gnome-custom bash ux <<<'

[[ -d "$source_dir" ]] || { echo "shell source directory missing: $source_dir" >&2; exit 20; }
mkdir -p "$target_dir" "$state_dir"
[[ -e "$bashrc" ]] || : >"$bashrc"

backup="$state_dir/bashrc.pre-fgc"
if [[ ! -e "$backup" ]]; then
  cp -p -- "$bashrc" "$backup"
fi

for file in init.sh history.sh aliases.sh navigation.sh completion.sh prompt.sh; do
  install -m 0644 "$source_dir/$file" "$target_dir/$file"
done

cat >"$target_dir/settings.sh" <<EOF_SETTINGS
# Generated by FEDORA_GNOME_CUSTOM. Edit config/local.conf, not this file.
FGC_HISTSIZE="${FGC_HISTSIZE:-50000}"
FGC_HISTFILESIZE="${FGC_HISTFILESIZE:-100000}"
FGC_ENABLE_FZF="${FGC_ENABLE_FZF:-true}"
FGC_ENABLE_ZOXIDE="${FGC_ENABLE_ZOXIDE:-true}"
FGC_ENABLE_DIRENV="${FGC_ENABLE_DIRENV:-true}"
FGC_PROMPT_GIT="${FGC_PROMPT_GIT:-true}"
EOF_SETTINGS
chmod 0644 "$target_dir/settings.sh"

mode="$(stat -c '%a' "$bashrc")"
tmp="$(mktemp "${bashrc}.fgc.XXXXXX")"
cleanup() { rm -f "$tmp"; }
trap cleanup EXIT
if ! awk -v start="$start_marker" -v end="$end_marker" '
  $0 == start { if (skip) exit 42; skip=1; next }
  $0 == end   { if (!skip) exit 43; skip=0; next }
  !skip { print }
  END { if (skip) exit 44 }
' "$bashrc" >"$tmp"; then
  echo 'existing FEDORA_GNOME_CUSTOM Bash block is malformed; refusing to rewrite .bashrc' >&2
  exit 21
fi

while [[ -s "$tmp" ]] && [[ "$(tail -c 1 "$tmp" | wc -l)" -eq 0 ]]; do
  printf '\n' >>"$tmp"
done
cat >>"$tmp" <<'EOF_BLOCK'
# >>> fedora-gnome-custom bash ux >>>
if [[ -r "${XDG_CONFIG_HOME:-$HOME/.config}/fedora-gnome-custom/bash/init.sh" ]]; then
  source "${XDG_CONFIG_HOME:-$HOME/.config}/fedora-gnome-custom/bash/init.sh"
fi
# <<< fedora-gnome-custom bash ux <<<
EOF_BLOCK
chmod "$mode" "$tmp"
mv -f -- "$tmp" "$bashrc"
trap - EXIT

printf 'Fedora Bash UX installed in %s\n' "$target_dir"
