# shellcheck shell=bash
# Fedora bash-completion plus cached completions generated by installed CLIs.
if [[ -r /usr/share/bash-completion/bash_completion ]] && ! declare -F _completion_loader >/dev/null 2>&1; then
  # shellcheck source=/dev/null
  source /usr/share/bash-completion/bash_completion
fi

__fgc_cache_completion() {
  local name="$1"
  shift
  local bin cache_dir cache tmp
  bin="$(type -P "$name" 2>/dev/null || true)"
  [[ -n "$bin" ]] || return 0
  cache_dir="${XDG_CACHE_HOME:-$HOME/.cache}/fedora-gnome-custom/bash-completions"
  cache="$cache_dir/$name.bash"
  mkdir -p "$cache_dir"
  if [[ ! -s "$cache" || "$bin" -nt "$cache" ]]; then
    tmp="$cache.tmp.$$"
    if "$@" >"$tmp" 2>/dev/null && [[ -s "$tmp" ]]; then
      mv -f "$tmp" "$cache"
    else
      rm -f "$tmp"
      return 0
    fi
  fi
  # shellcheck disable=SC1090
  source "$cache"
}

__fgc_cache_completion gh gh completion -s bash
__fgc_cache_completion glab glab completion -s bash
__fgc_cache_completion kubectl kubectl completion bash
__fgc_cache_completion helm helm completion bash
__fgc_cache_completion minikube minikube completion bash
unset -f __fgc_cache_completion
