GTK4_NATIVE_APPS_ONLY="true"
PROFESSIONAL_APPLICATION_EXCEPTIONS="true"
ENABLE_PROFESSIONAL_APPLICATIONS="true"
ENABLE_PROFESSIONAL_FLATPAKS="true"
VSCODE_PACKAGE="code"
BRAVE_PACKAGE="brave-browser"
TEXT_EDITOR_PACKAGE="gnome-text-editor"
TERMINAL_PACKAGE="ptyxis"
TERMINAL_DESKTOP_ID="org.gnome.Ptyxis.desktop"
