ENABLE_RPMFUSION="true"
ENABLE_FLATHUB="true"
ENABLE_GNOME_EXTENSIONS="false"
PRESERVE_FONT_RENDERING_DEFAULTS="true"
PRESERVE_DISPLAY_EXPERIMENTAL_DEFAULTS="true"
NAUTILUS_ENABLE_SMB="true"
NAUTILUS_ENABLE_MTP="true"
NAUTILUS_ENABLE_PREVIEWS="true"
