SYSTEMD_PERSISTENT_JOURNAL="true"
SYSTEMD_JOURNAL_MAX_USE="1G"
SYSTEMD_JOURNAL_RUNTIME_MAX_USE="256M"
SYSTEMD_JOURNAL_RETENTION="30day"
SYSTEMD_COREDUMP_STORAGE="external"
SYSTEMD_COREDUMP_MAX_USE="4G"
SYSTEMD_COREDUMP_KEEP_FREE="2G"
SYSTEMD_ENABLE_BOOT_HEALTH="true"
SYSTEMD_ENABLE_RESUME_HEALTH="true"
SYSTEMD_ENABLE_KDUMP_AUTOMATIC="false"
SYSTEMD_ENABLE_HARDWARE_WATCHDOG_AUTOMATIC="false"
