#!/usr/bin/env bash
set -Eeuo pipefail
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
lock="$REPO_ROOT/installer/fedora44-media.lock"
[[ -r "$lock" ]] || { echo "Missing Fedora media lock: $lock" >&2; exit 2; }
# shellcheck disable=SC1090
source "$lock"
usage(){ echo "Usage: $0 --disk /dev/nvmeXnY [--username mathias] [--hostname fedora-gnome-devops] [--output fedora44.ks]" >&2; }
disk=""; username="mathias"; hostname="fedora-gnome-devops"; output="fedora44-golden-workstation.ks"
while (($#)); do case "$1" in --disk) disk="${2:-}"; shift 2;; --username) username="${2:-}"; shift 2;; --hostname) hostname="${2:-}"; shift 2;; --output) output="${2:-}"; shift 2;; *) usage; exit 2;; esac; done
[[ -b "$disk" ]] || { usage; echo 'Target disk must be an existing block device.' >&2; exit 2; }
[[ "$disk" == /dev/nvme*n* ]] || { echo 'Refusing non-NVMe target for this hardware profile.' >&2; exit 2; }
repo_sha="$(git -C "$REPO_ROOT" rev-parse HEAD 2>/dev/null || true)"; [[ "$repo_sha" =~ ^[0-9a-f]{40,64}$ ]] || { echo 'Repository HEAD SHA cannot be resolved; generate Kickstart from a Git checkout.' >&2; exit 2; }
disk_name="${disk#/dev/}"
echo 'TARGET DISK:'; lsblk -d -o NAME,MODEL,SERIAL,SIZE,TRAN "$disk"
printf 'Repository SHA pinned into Kickstart: %s\n' "$repo_sha"
printf 'Approved Fedora media: %s (compose %s, sha256 %s)\n' "$ISO_FILENAME" "$FEDORA_COMPOSE" "$ISO_SHA256"
printf 'This generated Kickstart WILL erase only %s when used by Anaconda. Type exactly "EFFACER %s": ' "$disk" "$disk"
read -r answer; [[ "$answer" == "EFFACER $disk" ]] || { echo 'Cancelled.'; exit 2; }
read -rsp "Password for $username: " pass; echo; read -rsp 'Confirm password: ' pass2; echo; [[ "$pass" == "$pass2" && -n "$pass" ]] || { echo 'Passwords do not match.' >&2; exit 2; }
command -v openssl >/dev/null || { echo 'openssl is required to generate the Kickstart password hash.' >&2; exit 2; }
hash="$(printf '%s' "$pass" | openssl passwd -6 -stdin)"; unset pass pass2
cat > "$output" <<EOF_KS
# Generated by FEDORA_GNOME_CUSTOM. Review before use.
# Repository SHA: ${repo_sha}
# Approved Fedora release/compose: ${FEDORA_RELEASE}/${FEDORA_COMPOSE}
# Approved source ISO: ${ISO_FILENAME}
# Approved source ISO SHA256: ${ISO_SHA256}
text
lang fr_FR.UTF-8
keyboard fr
network --bootproto=dhcp --device=link --activate --hostname=${hostname}
timezone America/Martinique --utc
rootpw --lock
user --name=${username} --groups=wheel --password='${hash}' --iscrypted
firewall --enabled
selinux --enforcing
services --enabled=NetworkManager,firewalld --disabled=sshd
bootloader --location=boot --boot-drive=${disk_name}
ignoredisk --only-use=${disk_name}
clearpart --all --initlabel --drives=${disk_name}
autopart --type=btrfs
reboot

%packages
@^workstation-product-environment
git
curl
ca-certificates
sudo
dnf5-plugins
mokutil
openssh-clients
%end

%post --interpreter=/usr/bin/bash --log=/root/fedora-gnome-custom-kickstart-post.log
set -Eeuo pipefail
repo=/home/${username}/FEDORA_GNOME_CUSTOM
install -d -o ${username} -g ${username} -m 0755 "\$repo"
runuser -u ${username} -- git -C "\$repo" init
runuser -u ${username} -- git -C "\$repo" remote add origin https://github.com/mathiasseguincadiche/FEDORA_GNOME_CUSTOM.git
runuser -u ${username} -- git -C "\$repo" fetch --depth 1 origin ${repo_sha}
runuser -u ${username} -- git -C "\$repo" checkout --detach FETCH_HEAD
actual_sha="\$(runuser -u ${username} -- git -C "\$repo" rev-parse HEAD)"
[[ "\$actual_sha" == "${repo_sha}" ]]
chown -R ${username}:${username} "\$repo"
%end
EOF_KS
chmod 0600 "$output"
echo "Generated: $output"
echo 'The file contains a password hash and destructive disk instructions. Keep it private and review it before installation.'
