#!/usr/bin/env bash
set -Eeuo pipefail
usage(){ echo "Usage: $0 --disk /dev/nvmeXnY [--username mathias] [--hostname fedora-gnome-devops] [--output fedora44.ks]" >&2; }
disk=""; username="mathias"; hostname="fedora-gnome-devops"; output="fedora44-golden-workstation.ks"
while (($#)); do case "$1" in --disk) disk="${2:-}"; shift 2;; --username) username="${2:-}"; shift 2;; --hostname) hostname="${2:-}"; shift 2;; --output) output="${2:-}"; shift 2;; *) usage; exit 2;; esac; done
[[ -b "$disk" ]] || { usage; echo 'Target disk must be an existing block device.' >&2; exit 2; }
[[ "$disk" == /dev/nvme*n* ]] || { echo 'Refusing non-NVMe target for this hardware profile.' >&2; exit 2; }
disk_name="${disk#/dev/}"
echo 'TARGET DISK:'; lsblk -d -o NAME,MODEL,SERIAL,SIZE,TRAN "$disk"
printf 'This generated Kickstart WILL erase only %s when used by Anaconda. Type exactly "EFFACER %s": ' "$disk" "$disk"
read -r answer; [[ "$answer" == "EFFACER $disk" ]] || { echo 'Cancelled.'; exit 2; }
read -rsp "Password for $username: " pass; echo; read -rsp 'Confirm password: ' pass2; echo; [[ "$pass" == "$pass2" && -n "$pass" ]] || { echo 'Passwords do not match.' >&2; exit 2; }
command -v openssl >/dev/null || { echo 'openssl is required to generate the Kickstart password hash.' >&2; exit 2; }
hash="$(printf '%s' "$pass" | openssl passwd -6 -stdin)"; unset pass pass2
cat > "$output" <<EOF
# Generated by FEDORA_GNOME_CUSTOM. Review before use.
text
lang fr_FR.UTF-8
keyboard fr
network --bootproto=dhcp --device=link --activate --hostname=${hostname}
timezone America/Martinique --utc
rootpw --lock
user --name=${username} --groups=wheel --password='${hash}' --iscrypted
firewall --enabled
selinux --enforcing
services --enabled=NetworkManager,firewalld,sshd
bootloader --location=boot --boot-drive=${disk_name}
ignoredisk --only-use=${disk_name}
clearpart --all --initlabel --drives=${disk_name}
autopart --type=btrfs
reboot

%packages
@^workstation-product-environment
git
curl
ca-certificates
sudo
dnf5-plugins
mokutil
%end

%post --log=/root/fedora-gnome-custom-kickstart-post.log
set -e
install -d -m 0755 /home/${username}
if command -v git >/dev/null 2>&1; then
  runuser -u ${username} -- git clone https://github.com/mathiasseguincadiche/FEDORA_GNOME_CUSTOM.git /home/${username}/FEDORA_GNOME_CUSTOM || true
  chown -R ${username}:${username} /home/${username}/FEDORA_GNOME_CUSTOM 2>/dev/null || true
fi
%end
EOF
chmod 0600 "$output"
echo "Generated: $output"
echo 'The file contains a password hash and destructive disk instructions. Keep it private and review it before installation.'
